# Generated by Django 5.1.6 on 2025-03-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_mobile', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='myapp.users', to_field='mobile')),
            ],
        ),
    ]
