# Generated by Django 5.1.6 on 2025-03-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referred_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_income', to='myapp.users', to_field='mobile')),
            ],
        ),
    ]
