# Generated by Django 5.1.6 on 2025-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_monthlyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='referred_user_id',
            field=models.IntegerField(default='0'),
        ),
    ]
