# Generated by Django 5.1.6 on 2025-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_refund_referred_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='referred_user_id',
        ),
        migrations.AddField(
            model_name='refund',
            name='referred_user_mobile',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
