# Generated by Django 5.1.6 on 2025-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_refund_referred_user_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('user_mobile', 'referred_user_mobile'), name='unique_refund_entry'),
        ),
    ]
