# Generated by Django 5.1.6 on 2025-03-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_refund_unique_refund_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='membership_level',
            field=models.IntegerField(default=0),
        ),
    ]
