# Generated by Django 5.1.6 on 2025-03-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_users_membership_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refund',
            name='unique_refund_entry',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='referred_user_mobile',
        ),
    ]
