# Generated by Django 5.1.6 on 2025-03-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='user_mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='myapp.users', to_field='mobile'),
        ),
    ]
