# Generated by Django 5.1.6 on 2025-03-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_users_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='total_refunded',
        ),
    ]
