# Generated by Django 5.1.6 on 2025-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_wallet_total_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='refund_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=1),
        ),
    ]
