# Generated by Django 5.1.6 on 2025-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_referral_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='refund_status',
            field=models.CharField(choices=[('0', 'No Refund'), ('1', 'Partial Refund'), ('2', 'Full Refund')], default='0', max_length=1),
        ),
    ]
