# Generated by Django 5.1.6 on 2025-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_users_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_logged_in',
            field=models.CharField(choices=[('0', 'User is logged out'), ('1', 'User is logged in')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=0),
        ),
    ]
