# Generated by Django 5.1.6 on 2025-03-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
