# Generated by Django 5.1.6 on 2025-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_users_is_logged_in_remove_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_logged_in',
            field=models.CharField(choices=[('0', 'User is logged out'), ('1', 'User is logged in')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
