# Generated by Django 5.1.6 on 2025-03-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_users_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.users', to_field='mobile'),
        ),
    ]
