# Generated by Django 5.1.6 on 2025-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_payment_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(upload_to='membership'),
        ),
    ]
