# Generated by Django 5.1.6 on 2025-03-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='myapp.users', to_field='mobile')),
            ],
        ),
    ]
