# Generated by Django 5.1.6 on 2025-03-21 10:53

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.pan_card_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
