# Generated by Django 5.1.6 on 2025-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
