# Generated by Django 5.1.6 on 2025-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_bankdetails_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
