# Generated by Django 5.1.6 on 2025-03-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
