# Generated by Django 5.1.6 on 2025-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_payment_transaction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.IntegerField(default=0),
        ),
    ]
