# Generated by Django 5.1.6 on 2025-03-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_payment_transaction_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='screenshot',
        ),
    ]
