# Generated by Django 5.1.6 on 2025-03-25 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
