# Generated by Django 5.1.6 on 2025-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_payment_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='tds_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
