# Generated by Django 5.1.6 on 2025-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_wallet_tds_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='refund_status',
            field=models.CharField(choices=[('0', 'No Refund'), ('1', 'Full Refund')], default='0', max_length=1),
        ),
    ]
