# Generated by Django 5.1.6 on 2025-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_gallery_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='status',
        ),
    ]
