# Generated by Django 5.1.6 on 2025-03-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id',
            field=models.IntegerField(default=0),
        ),
    ]
