# Generated by Django 5.1.6 on 2025-03-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_supportticket_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=500)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('user_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_videos', to='myapp.users', to_field='mobile')),
            ],
        ),
    ]
