# Generated by Django 5.1.6 on 2025-03-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_watchedvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
